import AppKit
import SwiftUI
import UniformTypeIdentifiers

enum ClipKind: String, Codable, CaseIterable, Sendable {
    case text, link, image, files
    var title: String { rawValue.capitalized }
    var symbol: String {
        switch self { case .text: "text.alignleft"; case .link: "link"; case .image: "photo"; case .files: "doc" }
    }
}

struct LocalClip: Identifiable, Codable, Equatable, Sendable {
    var id = UUID()
    var createdAt = Date()
    let kind: ClipKind
    var text: String?
    var image: Data?
    var imageType: String?
    var files: [URL] = []
    var title: String {
        switch kind {
        case .text, .link: String((text ?? "").prefix(140))
        case .image: "Image · \((image?.count ?? 0).formatted(.byteCount(style: .file)))"
        case .files: files.map(\.lastPathComponent).joined(separator: ", ")
        }
    }
    var byteCount: Int { (image?.count ?? 0) + (text?.utf8.count ?? 0) + files.reduce(0) { $0 + $1.path.utf8.count } }
    func sameContent(as other: LocalClip) -> Bool {
        kind == other.kind && text == other.text && image == other.image && files == other.files
    }
}

@MainActor
final class ClipboardToolStore: ObservableObject {
    private static var instance: ClipboardToolStore?
    static var shared: ClipboardToolStore {
        if let instance { return instance }
        let store = ClipboardToolStore()
        instance = store
        return store
    }
    static func shutdownIfInitialized() { instance?.setObserving(false) }

    @Published private(set) var clips: [LocalClip] = []
    @Published private(set) var observing = false
    @Published var error: String?
    @Published var status = "Observation is off."
    private var observation: Task<Void, Never>?
    private var lastCount = 0
    private let limit = 100
    private let totalByteLimit = 20 * 1_024 * 1_024
    private let pasteboard: NSPasteboard
    private let persistHistory: Bool

    init(pasteboard: NSPasteboard? = nil, persistHistory: Bool = true) {
        self.pasteboard = pasteboard ?? .general
        self.persistHistory = persistHistory
        guard persistHistory else { return }
        do {
            clips = try LocalToolStorage.load([LocalClip].self, file: "clipboard.json", fallback: [])
            boundHistory()
        } catch { self.error = "Could not load clipboard history: \(error.localizedDescription)" }
    }
    deinit { observation?.cancel() }

    func setObserving(_ enabled: Bool) {
        observation?.cancel()
        observation = nil
        observing = enabled
        guard enabled else { status = "Observation is off."; return }
        lastCount = pasteboard.changeCount
        status = "Watching new copies on this Mac, including while the panel is hidden."
        observation = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                do { try await Task.sleep(for: .milliseconds(700)) } catch { return }
                guard let self else { return }
                self.captureIfChanged()
            }
        }
    }

    func captureIfChanged() {
        guard observing else { return }
        let board = pasteboard
        guard board.changeCount != lastCount else { return }
        lastCount = board.changeCount
        let types = (board.types ?? []) + (board.pasteboardItems ?? []).flatMap(\.types)
        let concealed = types.contains { type in
            let name = type.rawValue.lowercased()
            return ["concealed", "transient", "autogenerated", "password", "onepassword", "1password",
                    "lastpass", "keepass", "bitwarden", "application/x-secret"].contains { name.contains($0) }
        }
        let owner = board.string(forType: .init("org.nspasteboard.source"))?.lowercased() ?? ""
        guard !concealed, !["1password", "onepassword", "lastpass", "keepass", "bitwarden"].contains(where: owner.contains) else {
            status = "Skipped private or transient clipboard content."
            return
        }
        let clip: LocalClip?
        let files = (board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [NSURL] ?? [])
            .map { $0 as URL }.filter { $0.isFileURL && (($0.host ?? "").isEmpty || $0.host == "localhost") }
        if !files.isEmpty {
            clip = LocalClip(kind: .files, files: Array(files.prefix(200)))
        } else if let image = board.data(forType: .png), image.count <= 4 * 1_024 * 1_024 {
            clip = LocalClip(kind: .image, image: image, imageType: NSPasteboard.PasteboardType.png.rawValue)
        } else if let image = board.data(forType: .tiff), image.count <= 4 * 1_024 * 1_024 {
            clip = LocalClip(kind: .image, image: image, imageType: NSPasteboard.PasteboardType.tiff.rawValue)
        } else if let type = (board.types ?? []).first(where: { UTType($0.rawValue)?.conforms(to: .image) == true }),
                  let image = board.data(forType: type), image.count <= 4 * 1_024 * 1_024 {
            clip = LocalClip(kind: .image, image: image, imageType: type.rawValue)
        } else if let value = board.string(forType: .string) ?? board.string(forType: .URL), !value.isEmpty {
            guard value.utf8.count <= 100_000 else { status = "Skipped text larger than 100 KB."; return }
            let url = URL(string: value.trimmingCharacters(in: .whitespacesAndNewlines))
            let isLink = ["http", "https", "mailto"].contains(url?.scheme?.lowercased() ?? "")
            clip = LocalClip(kind: isLink ? .link : .text, text: value)
        } else {
            status = "Skipped unsupported clipboard content or an image larger than 4 MB."
            return
        }
        guard let clip, board.changeCount == lastCount else { return }
        if let first = clips.first, first.sameContent(as: clip) { return }
        clips.insert(clip, at: 0)
        boundHistory()
        save()
        status = "Saved \(clip.kind.title.lowercased()) locally."
    }

    private func boundHistory() {
        clips = Array(clips.prefix(limit))
        while clips.reduce(0, { $0 + $1.byteCount }) > totalByteLimit { clips.removeLast() }
    }
    private func save() {
        guard persistHistory else { return }
        do { try LocalToolStorage.save(clips, file: "clipboard.json"); error = nil }
        catch { self.error = "Could not save clipboard history: \(error.localizedDescription)" }
    }
    func clear() { clips.removeAll(); save(); status = "History cleared." }
    func remove(_ clip: LocalClip) { clips.removeAll { $0.id == clip.id }; save() }
    func copy(_ clip: LocalClip) {
        let board = pasteboard
        board.clearContents()
        let success: Bool
        switch clip.kind {
        case .text, .link: success = board.setString(clip.text ?? "", forType: .string)
        case .image:
            if let data = clip.image, let type = clip.imageType {
                success = board.setData(data, forType: .init(type))
            } else { success = false }
        case .files:
            guard clip.files.allSatisfy({ FileManager.default.fileExists(atPath: $0.path) }) else {
                error = "A file in this clip has moved or is no longer available."
                return
            }
            success = board.writeObjects(clip.files.map { $0 as NSURL })
        }
        lastCount = board.changeCount
        if success { status = "Copied again."; error = nil }
        else { error = "macOS could not write this clip to the clipboard." }
    }
}

@MainActor
struct ClipboardToolView: View {
    @ObservedObject private var store = ClipboardToolStore.shared
    @State private var search = ""
    @State private var filter = "all"
    private var visible: [LocalClip] {
        store.clips.filter { (filter == "all" || $0.kind.rawValue == filter) &&
            (search.isEmpty || $0.title.localizedCaseInsensitiveContains(search) ||
             ($0.text?.localizedCaseInsensitiveContains(search) ?? false)) }
    }
    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Toggle("Observe clipboard", isOn: Binding(get: { store.observing }, set: { enabled in
                    store.setObserving(enabled)
                }))
                Spacer()
                Button("Clear History", action: store.clear).disabled(store.clips.isEmpty)
            }
            Text("Off at every launch; once enabled, keeps observing while hidden. Known concealed, transient, and password-manager clips are skipped.")
                .font(.caption).foregroundStyle(.secondary)
            HStack {
                TextField("Search history", text: $search).textFieldStyle(.roundedBorder)
                Picker("Kind", selection: $filter) {
                    Text("All").tag("all")
                    ForEach(ClipKind.allCases, id: \.rawValue) { Text($0.title).tag($0.rawValue) }
                }.frame(width: 120)
            }
            LocalToolError(message: store.error)
            List(visible) { clip in
                HStack {
                    Button {
                        if NSEvent.modifierFlags.contains(.option) { store.remove(clip) }
                        else { store.copy(clip) }
                    } label: {
                        HStack(alignment: .top) {
                            if let data = clip.image, let image = NSImage(data: data) {
                                Image(nsImage: image).resizable().scaledToFit().frame(width: 32, height: 32)
                            } else { Image(systemName: clip.kind.symbol).frame(width: 24) }
                            VStack(alignment: .leading) {
                                Text(clip.title).lineLimit(2).frame(maxWidth: .infinity, alignment: .leading)
                                Text(clip.createdAt, style: .relative).font(.caption2).foregroundStyle(.secondary)
                            }
                        }
                    }.buttonStyle(.plain).accessibilityLabel("Copy \(clip.kind.title): \(clip.title)")
                    Button { store.remove(clip) } label: { Image(systemName: "trash") }
                        .buttonStyle(.borderless).help("Delete clip").accessibilityLabel("Delete clip")
                }.contextMenu {
                    Button("Copy Again") { store.copy(clip) }
                    Button("Delete", role: .destructive) { store.remove(clip) }
                }
            }.frame(height: 200)
            HStack {
                Text(store.status).font(.caption).foregroundStyle(.secondary)
                Spacer()
                Text("\(store.clips.count)/100 · 20 MB maximum · ⌥-click deletes")
                    .font(.caption2).foregroundStyle(.secondary)
            }
        }.padding()
    }
}
