#!/usr/bin/env python3
"""Generate an isolated Xcode project; reuse the original engines without copying them."""
from pathlib import Path
import hashlib
import json
import os
import sys

ROOT = Path(__file__).resolve().parent.parent
REPOSITORY = ROOT.parent
PROJECT = ROOT / "NotchOrbit.xcodeproj"
CHECK = "--check" in sys.argv[1:]
if set(sys.argv[1:]) - {"--check"}:
    raise SystemExit("Usage: python3 Scripts/generate-project.py [--check]")


def ident(name):
    return hashlib.sha1(name.encode()).hexdigest()[:24].upper()


def quote(value):
    return json.dumps(str(value))


def relative(path):
    return Path(os.path.relpath(path, ROOT)).as_posix()


objects = []


def obj(key, isa, fields):
    objects.append(f"\t\t{ident(key)} = {{ isa = {isa}; {fields} }};")
    return ident(key)


def refs(keys):
    return "(" + ", ".join(ident(key) for key in keys) + ")"


sources = {
    "OrbitCore": sorted((REPOSITORY / "Sources/OrbitCore").glob("*.swift")),
    "NotchCore": sorted((ROOT / "Sources/NotchCore").glob("**/*.swift")),
    "NotchOrbit": sorted((ROOT / "Sources/NotchOrbit").glob("**/*.swift"))
        + [REPOSITORY / "Sources/OrbitDrop/AppModel.swift"]
        + sorted((REPOSITORY / "Sources/OrbitDrop/Engines").glob("**/*.swift")),
    "NotchOrbitTests": sorted((ROOT / "Tests/NotchOrbitTests").glob("**/*.swift")),
}
if not all(sources.values()) or not all(path.is_file() for paths in sources.values() for path in paths):
    raise SystemExit("All four targets need their source files before project generation.")
sources = {target: sorted(paths, key=relative) for target, paths in sources.items()}

file_keys = []
for target, paths in sources.items():
    for path in paths:
        name = relative(path)
        key = "file:" + name
        file_keys.append(key)
        obj(key, "PBXFileReference", f"lastKnownFileType = sourcecode.swift; path = {quote(name)}; sourceTree = SOURCE_ROOT;")
        obj("build:" + name, "PBXBuildFile", f"fileRef = {ident(key)};")

# Generated by make-icon.sh before xcodebuild. Keep the original app's assets untouched.
obj("file:icon", "PBXFileReference", 'lastKnownFileType = image.icns; path = build/AppIcon.icns; sourceTree = SOURCE_ROOT;')
obj("resource:icon", "PBXBuildFile", f"fileRef = {ident('file:icon')};")
file_keys.append("file:icon")
products = {
    "OrbitCore": ("libOrbitCore.a", "archive.ar"),
    "NotchCore": ("libNotchCore.a", "archive.ar"),
    "NotchOrbit": ("NotchOrbit.app", "wrapper.application"),
    "NotchOrbitTests": ("NotchOrbitTests.xctest", "wrapper.cfbundle"),
}
for target, (name, kind) in products.items():
    obj("product:" + target, "PBXFileReference", f"explicitFileType = {kind}; includeInIndex = 0; path = {name}; sourceTree = BUILT_PRODUCTS_DIR;")
obj("group:products", "PBXGroup", f"children = {refs(['product:' + t for t in products])}; name = Products; sourceTree = \"<group>\";")
obj("group:main", "PBXGroup", f"children = {refs(file_keys + ['group:products'])}; sourceTree = \"<group>\";")

dependencies = {
    "OrbitCore": [], "NotchCore": [],
    "NotchOrbit": ["OrbitCore", "NotchCore"],
    "NotchOrbitTests": ["OrbitCore", "NotchCore", "NotchOrbit"],
}
for target, deps in dependencies.items():
    dependency_keys = []
    for dependency in deps:
        key = f"dependency:{target}:{dependency}"
        proxy = key + ":proxy"
        obj(proxy, "PBXContainerItemProxy", f"containerPortal = {ident('project')}; proxyType = 1; remoteGlobalIDString = {ident('target:' + dependency)}; remoteInfo = {dependency};")
        obj(key, "PBXTargetDependency", f"target = {ident('target:' + dependency)}; targetProxy = {ident(proxy)};")
        dependency_keys.append(key)
    build_keys = ["build:" + relative(path) for path in sources[target]]
    obj("sources:" + target, "PBXSourcesBuildPhase", f"buildActionMask = 2147483647; files = {refs(build_keys)}; runOnlyForDeploymentPostprocessing = 0;")
    links = []
    for dependency in deps:
        if dependency not in {"OrbitCore", "NotchCore"}:
            continue
        link = f"link:{target}:{dependency}"
        obj(link, "PBXBuildFile", f"fileRef = {ident('product:' + dependency)};")
        links.append(link)
    obj("frameworks:" + target, "PBXFrameworksBuildPhase", f"buildActionMask = 2147483647; files = {refs(links)}; runOnlyForDeploymentPostprocessing = 0;")
    obj("resources:" + target, "PBXResourcesBuildPhase", f"buildActionMask = 2147483647; files = {refs(['resource:icon'] if target == 'NotchOrbit' else [])}; runOnlyForDeploymentPostprocessing = 0;")
    product_type = ("com.apple.product-type.library.static" if target in {"OrbitCore", "NotchCore"}
                    else "com.apple.product-type.application" if target == "NotchOrbit"
                    else "com.apple.product-type.bundle.unit-test")
    phases = ["sources:" + target, "frameworks:" + target, "resources:" + target]
    obj("target:" + target, "PBXNativeTarget", f"buildConfigurationList = {ident('configs:' + target)}; buildPhases = {refs(phases)}; buildRules = (); dependencies = {refs(dependency_keys)}; name = {target}; productName = {target}; productReference = {ident('product:' + target)}; productType = {quote(product_type)};")

for scope in ["project", *products]:
    keys = []
    for configuration in ["Debug", "Release"]:
        settings = {
            "SDKROOT": "macosx", "MACOSX_DEPLOYMENT_TARGET": "14.0", "SWIFT_VERSION": "6.0",
            "CLANG_ENABLE_MODULES": "YES", "SWIFT_STRICT_CONCURRENCY": "complete",
            "CODE_SIGNING_ALLOWED": "NO", "SUPPORTED_PLATFORMS": "macosx",
            "SWIFT_OPTIMIZATION_LEVEL": "-Onone" if configuration == "Debug" else "-O",
            "DEBUG_INFORMATION_FORMAT": "dwarf" if configuration == "Debug" else "dwarf-with-dsym",
            "ONLY_ACTIVE_ARCH": "YES" if configuration == "Debug" else "NO",
            "SWIFT_ACTIVE_COMPILATION_CONDITIONS": "DEBUG" if configuration == "Debug" else "",
        }
        if configuration == "Release":
            settings["ARCHS"] = "arm64 x86_64"
        if scope != "project":
            settings.update({"PRODUCT_NAME": "$(TARGET_NAME)", "PRODUCT_MODULE_NAME": scope,
                             "SWIFT_INCLUDE_PATHS": "$(inherited) $(BUILT_PRODUCTS_DIR)", "ENABLE_TESTABILITY": "YES"})
        if scope in {"OrbitCore", "NotchCore"}:
            settings.update({"DEFINES_MODULE": "YES", "MACH_O_TYPE": "staticlib", "SKIP_INSTALL": "YES", "SWIFT_INSTALL_OBJC_HEADER": "NO"})
        if scope == "NotchOrbit":
            settings.update({"INFOPLIST_FILE": "Resources/Info.plist", "PRODUCT_BUNDLE_IDENTIFIER": "com.sknitd.NotchOrbit",
                             "SWIFT_OBJC_BRIDGING_HEADER": "../Sources/OrbitDrop/WebPBridge.h",
                             "HEADER_SEARCH_PATHS": "$(inherited) $(SRCROOT)/../build/WebP/include",
                             "OTHER_LDFLAGS": "$(inherited) -L$(SRCROOT)/../build/WebP/lib -lwebp -lsharpyuv",
                             "LD_RUNPATH_SEARCH_PATHS": "$(inherited) @executable_path/../Frameworks"})
        if scope == "NotchOrbitTests":
            settings.update({"GENERATE_INFOPLIST_FILE": "YES", "PRODUCT_BUNDLE_IDENTIFIER": "com.sknitd.NotchOrbitTests",
                             "HEADER_SEARCH_PATHS": "$(inherited) $(SRCROOT)/../build/WebP/include",
                             "TEST_HOST": "$(BUILT_PRODUCTS_DIR)/NotchOrbit.app/Contents/MacOS/NotchOrbit",
                             "BUNDLE_LOADER": "$(TEST_HOST)",
                             "LD_RUNPATH_SEARCH_PATHS": "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks"})
        contents = " ".join(f"{key} = {quote(value)};" for key, value in sorted(settings.items()))
        key = f"config:{scope}:{configuration}"
        obj(key, "XCBuildConfiguration", f"buildSettings = {{ {contents} }}; name = {configuration};")
        keys.append(key)
    obj("configs:" + scope, "XCConfigurationList", f"buildConfigurations = {refs(keys)}; defaultConfigurationIsVisible = 0; defaultConfigurationName = Release;")
obj("project", "PBXProject", f"attributes = {{ LastUpgradeCheck = 1600; }}; buildConfigurationList = {ident('configs:project')}; compatibilityVersion = \"Xcode 14.0\"; developmentRegion = en; hasScannedForEncodings = 0; knownRegions = (en, Base); mainGroup = {ident('group:main')}; productRefGroup = {ident('group:products')}; projectDirPath = \"\"; projectRoot = \"\"; targets = {refs(['target:' + t for t in products])};")
project_text = "// !$*UTF8*$!\n{\n\tarchiveVersion = 1;\n\tclasses = {};\n\tobjectVersion = 56;\n\tobjects = {\n" + "\n".join(objects) + f"\n\t}};\n\trootObject = {ident('project')};\n}}\n"


def save_or_check(path, content):
    if CHECK:
        if not path.is_file() or path.read_text() != content:
            raise SystemExit(f"{path} needs updating. Run python3 Scripts/generate-project.py in NotchOrbit and review the generated project.")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


save_or_check(PROJECT / "project.pbxproj", project_text)


def buildable(target):
    return f'<BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="{ident("target:" + target)}" BuildableName="{products[target][0]}" BlueprintName="{target}" ReferencedContainer="container:NotchOrbit.xcodeproj"/>'


scheme = f'''<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="1600" version="1.3">
<BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES"><BuildActionEntries>
<BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">{buildable('NotchOrbit')}</BuildActionEntry>
<BuildActionEntry buildForTesting="YES" buildForRunning="NO" buildForProfiling="NO" buildForArchiving="NO" buildForAnalyzing="NO">{buildable('NotchOrbitTests')}</BuildActionEntry>
</BuildActionEntries></BuildAction>
<TestAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.IDEFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES"><Testables><TestableReference skipped="NO">{buildable('NotchOrbitTests')}</TestableReference></Testables></TestAction>
<LaunchAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.IDEFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugServiceExtension="internal" allowLocationSimulation="YES"><BuildableProductRunnable runnableDebuggingMode="0">{buildable('NotchOrbit')}</BuildableProductRunnable></LaunchAction>
<ProfileAction buildConfiguration="Release" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugServiceExtension="internal"><BuildableProductRunnable runnableDebuggingMode="0">{buildable('NotchOrbit')}</BuildableProductRunnable></ProfileAction>
<AnalyzeAction buildConfiguration="Debug"/><ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
</Scheme>'''
save_or_check(PROJECT / "xcshareddata/xcschemes/NotchOrbit.xcscheme", scheme)
print(f"{'Verified' if CHECK else 'Generated'} {PROJECT} ({sum(map(len, sources.values()))} source files, 4 targets)")
